services:
  app:
    build:
      context: /app
      dockerfile: packages/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      ORIGIN: http://localhost:3000
      SQLITE: http://turso:8080
    depends_on:
      turso:
        condition: service_started

  turso:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - '8080:8080'
    volumes:
      - turso_data:/var/lib/sqld

volumes:
  turso_data:
